const themeOption = {
  vintage: vintage,
  dark: dark,
  westeros: westeros,
  essos: essos,
  wonderland: wonderland,
  walden: walden,
  chalk: chalk,
  infographic: infographic,
  macarons: macarons,
  roma: roma,
  shine: shine,
  purple_passion: purple_passion,
  halloween: halloween,
  customed: customed,
}
